# values.yaml

service:
  type: NodePort

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



clusterClasses:
  - name: "classa"
    clusterCount: 1
    settings:
      autodeploy: {}
      #   file1: |
      #     multiline
      #     content
      #     for file1
      server:
        count: 1
        extraFlags:
          - "--cluster-cidr=10.52.0.0/16"
          - "--service-cidr=10.53.0.0/16"
        resources: 
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 128Mi
      kubectl:
        resources: {}
      agent:
        count: 3
        resources: 
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 75Mi
      k3sVersion: "v1.27.10-k3s2"
      kubectlVersion: "1.27.10"


  - name: "namespacetest"
    clusterCount: 1
    settings:
      autodeploy: {}
      namespace:
        name: "testspin"
        create: false
      server:
        count: 1
        extraFlags:
          - "--cluster-cidr=10.52.0.0/16"
          - "--service-cidr=10.53.0.0/16"
        resources: 
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 128Mi
      kubectl:
        resources: {}
      agent:
        count: 3
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 75Mi
      k3sVersion: "v1.27.10-k3s2"
      kubectlVersion: "1.27.10"   

  # - name: "classb"
  #   serverCount: 1
  #   agentCount: 2
  #   clusterCount: 3
  #   settings:
  #     # extraServerFlags:
  #     #   - "--some-flag"
  #     #   - "--another-flag"
  #     k3sVersion: "v1.27.10-k3s2"
  #     kubectlVersion: "1.27.10"
